### ISSUE TITLE
Drill doesn't mine down to bedrock

### ISSUE THREAD

**Issue by MasterEnderman** [Klebestreifen/Drilldown#1]
I use CoFH World to genrate Flat Bedrock in all dimensions.

y-Level| Block| Gets mined?
------------ | -------------  | -------------
0|Bedrock|no
1|stone / ore|no
2-254|stone / ore / erc. | yes

so the drill doesn't mine blocks below y-level 2 even if the block there isn't bedrock.

**Comment by Klebestreifen** [comment]
I changed a single character in the code. This should solve the problem. The new version (0.1.1) has already been submitted to CurseForge.
