### ISSUE TITLE
*Configurations*

### ISSUE THREAD

**Issue by MasterEnderman** [Klebestreifen/Drilldown#3]
This mod needs some basic config options.

- [ ] internal energy storage capacity
- [ ] energy per block cost
- [ ] mining speed of the drill (blocks per second)

**Comment by Klebestreifen** [comment]
I plan to bring this in with the new minor update to version 0.2.0.

**Comment by MasterEnderman** [comment]
maybe add a config to don't require power at all, so the block can be used in a vanilla playthrough aswell. together with the addition of a blacklist, it would be possible.

**Comment by Klebestreifen** [comment]
As already explained in #4 this is actually not planned to work without other mods.
